Ard-Base: actions.h File Reference
actions.h File Reference
#include <stdint.h>
#include <stdbool.h>
Macros
#define ACTIONS_MGR_H_GUARD
Typedefs
typedef void() Action_Callback(void)
Functions
void Actions_enableWallLightA (void)
void Actions_enableWallLightB (void)
void Actions_disableWallLightA (void)
void Actions_disableWallLightB (void)
void Actions_runBedLightTimer (void)
void Actions_enableBedLight (void)
void Actions_disableBedLight (void)
void Actions_toggleWallLightA (void)
void Actions_toggleWallLightB (void)
void Actions_toggleMainLight (void)
void Actions_disableAllLight (void)
void Actions_enableAllLight (void)
void Actions_disableWallLight (void)
void Actions_enableWallLight (void)
void Actions_toggleLed (void)
void Actions_enableLivingLightA (void)
void Actions_enableLivingLightB (void)
void Actions_disableLivingLightA (void)
void Actions_disableLivingLightB (void)
void Actions_enableKitchenLedLight (void)
void Actions_disableKitchenLedLight (void)
void Actions_toggleLivingLightA (void)
void Actions_toggleLivingLightB (void)
void Actions_toggleKitchenLedLight (void)
void Actions_toggleKitchenMainLight (void)
void Actions_disableKitchAllLight (void)
void Actions_enableKitchenAllLight (void)
void Actions_disableLivingLight (void)
void Actions_enableLivingLight (void)
Macro Definition Documentation
ACTIONS_MGR_H_GUARD
#define ACTIONS_MGR_H_GUARD
Typedef Documentation
Action_Callback
typedef void() Action_Callback(void)
Function Documentation
Actions_disableAllLight()
void Actions_disableAllLight (void)
References GPIO_PIN_RELAY1, GPIO_PIN_RELAY2, GPIO_PIN_RELAY3, Gpio_SetPinState(), LOG_DEBUG, and LOGGERLN.
Actions_disableBedLight()
void Actions_disableBedLight (void)
References GPIO_PIN_RELAY4, Gpio_SetPinState(), LOG_DEBUG, and LOGGERLN.
Actions_disableKitchAllLight()
void Actions_disableKitchAllLight (void)
References GPIO_PIN_RELAY1, GPIO_PIN_RELAY2, GPIO_PIN_RELAY3, GPIO_PIN_RELAY4, Gpio_SetPinState(), LOG_DEBUG, and LOGGERLN.
Actions_disableKitchenLedLight()
void Actions_disableKitchenLedLight (void)
References GPIO_PIN_RELAY4, Gpio_SetPinState(), LOG_DEBUG, and LOGGERLN.
Actions_disableLivingLight()
void Actions_disableLivingLight (void)
References GPIO_PIN_RELAY1, GPIO_PIN_RELAY2, Gpio_SetPinState(), LOG_DEBUG, and LOGGERLN.
Actions_disableLivingLightA()
void Actions_disableLivingLightA (void)
References GPIO_PIN_RELAY1, Gpio_SetPinState(), LOG_DEBUG, and LOGGERLN.
Actions_disableLivingLightB()
void Actions_disableLivingLightB (void)
References GPIO_PIN_RELAY2, Gpio_SetPinState(), LOG_DEBUG, and LOGGERLN.
Actions_disableWallLight()
void Actions_disableWallLight (void)
References GPIO_PIN_RELAY1, GPIO_PIN_RELAY2, Gpio_SetPinState(), LOG_DEBUG, and LOGGERLN.
Actions_disableWallLightA()
void Actions_disableWallLightA (void)
References GPIO_PIN_RELAY1, Gpio_SetPinState(), LOG_DEBUG, and LOGGERLN.
Actions_disableWallLightB()
void Actions_disableWallLightB (void)
References GPIO_PIN_RELAY2, Gpio_SetPinState(), LOG_DEBUG, and LOGGERLN.
Actions_enableAllLight()
void Actions_enableAllLight (void)
References GPIO_PIN_RELAY1, GPIO_PIN_RELAY2, GPIO_PIN_RELAY3, Gpio_SetPinState(), LOG_DEBUG, and LOGGERLN.
Actions_enableBedLight()
void Actions_enableBedLight (void)
References GPIO_PIN_RELAY4, Gpio_SetPinState(), LOG_DEBUG, LOGGERLN, TIMER_BED_LIGHT, and Timer_Stop().
Actions_enableKitchenAllLight()
void Actions_enableKitchenAllLight (void)
References GPIO_PIN_RELAY1, GPIO_PIN_RELAY2, GPIO_PIN_RELAY3, GPIO_PIN_RELAY4, Gpio_SetPinState(), LOG_DEBUG, and LOGGERLN.
Actions_enableKitchenLedLight()
void Actions_enableKitchenLedLight (void)
References GPIO_PIN_RELAY4, Gpio_SetPinState(), LOG_DEBUG, and LOGGERLN.
Actions_enableLivingLight()
void Actions_enableLivingLight (void)
References GPIO_PIN_RELAY1, GPIO_PIN_RELAY2, Gpio_SetPinState(), LOG_DEBUG, and LOGGER.
Actions_enableLivingLightA()
void Actions_enableLivingLightA (void)
References GPIO_PIN_RELAY1, Gpio_SetPinState(), LOG_DEBUG, and LOGGERLN.
Actions_enableLivingLightB()
void Actions_enableLivingLightB (void)
References GPIO_PIN_RELAY2, Gpio_SetPinState(), LOG_DEBUG, and LOGGERLN.
Actions_enableWallLight()
void Actions_enableWallLight (void)
References GPIO_PIN_RELAY1, GPIO_PIN_RELAY2, Gpio_SetPinState(), LOG_DEBUG, and LOGGER.
Actions_enableWallLightA()
void Actions_enableWallLightA (void)
References GPIO_PIN_RELAY1, Gpio_SetPinState(), LOG_DEBUG, and LOGGERLN.
Actions_enableWallLightB()
void Actions_enableWallLightB (void)
References GPIO_PIN_RELAY2, Gpio_SetPinState(), LOG_DEBUG, and LOGGERLN.
Actions_runBedLightTimer()
void Actions_runBedLightTimer (void)
References LOG_DEBUG, LOGGERLN, TIMER_BED_LIGHT, and Timer_Run().
Actions_toggleKitchenLedLight()
void Actions_toggleKitchenLedLight (void)
References Gpio_GetPinState(), GPIO_PIN_RELAY4, Gpio_SetPinState(), LOG_DEBUG, LOG_VERBOSE, LOGGER, and LOGGERLN.
Actions_toggleKitchenMainLight()
void Actions_toggleKitchenMainLight (void)
References Gpio_GetPinState(), GPIO_PIN_RELAY3, Gpio_SetPinState(), LOG_DEBUG, LOG_VERBOSE, LOGGER, and LOGGERLN.
Actions_toggleLed()
void Actions_toggleLed (void)
References Gpio_GetPinState(), GPIO_PIN_LED, Gpio_SetPinState(), LOG_INFO, and LOGGER.
Actions_toggleLivingLightA()
void Actions_toggleLivingLightA (void)
References Gpio_GetPinState(), GPIO_PIN_RELAY1, Gpio_SetPinState(), LOG_DEBUG, LOG_VERBOSE, LOGGER, and LOGGERLN.
Actions_toggleLivingLightB()
void Actions_toggleLivingLightB (void)
References Gpio_GetPinState(), GPIO_PIN_RELAY2, Gpio_SetPinState(), LOG_DEBUG, LOG_VERBOSE, LOGGER, and LOGGERLN.
Actions_toggleMainLight()
void Actions_toggleMainLight (void)
References Gpio_GetPinState(), GPIO_PIN_RELAY3, Gpio_SetPinState(), LOG_DEBUG, LOG_VERBOSE, LOGGER, and LOGGERLN.
Actions_toggleWallLightA()
void Actions_toggleWallLightA (void)
References Gpio_GetPinState(), GPIO_PIN_RELAY1, Gpio_SetPinState(), LOG_DEBUG, LOG_VERBOSE, LOGGER, and LOGGERLN.
Actions_toggleWallLightB()
void Actions_toggleWallLightB (void)
References Gpio_GetPinState(), GPIO_PIN_RELAY2, Gpio_SetPinState(), LOG_DEBUG, LOG_VERBOSE, LOGGER, and LOGGERLN.