Ard-Base: button.h File Reference
button.h File Reference
#include "gpio.h"
Data Structures
struct Button_Struct
Typedefs
typedef void(* Button_Callback) (void)
Enumerations
enum Button_State {
BUTTON_STATE_SHORT_RELEASED, BUTTON_STATE_SHORT_PRESS, BUTTON_STATE_LONG_PRESS, BUTTON_STATE_LONG_RELEASED,
BUTTON_STATE_SUPERLONG_PRESS, BUTTON_STATE_SUPERLONG_RELEASED, BUTTON_STATE_SENTINEL
}
Functions
void buttonTask (void)
Button_Struct * Button_FindHandler (Gpio_Pin pinName)
Typedef Documentation
Button_Callback
typedef void(* Button_Callback) (void)
Enumeration Type Documentation
Button_State
enum Button_State
Enumerator
BUTTON_STATE_SHORT_RELEASED
BUTTON_STATE_SHORT_PRESS
BUTTON_STATE_LONG_PRESS
BUTTON_STATE_LONG_RELEASED
BUTTON_STATE_SUPERLONG_PRESS
BUTTON_STATE_SUPERLONG_RELEASED
BUTTON_STATE_SENTINEL
Function Documentation
Button_FindHandler()
Button_Struct* Button_FindHandler (Gpio_Pin pinName)
References buttonStateMatrix, and Button_Struct::pinName.
Referenced by EventMgrInit().
buttonTask()
void buttonTask (void)
References buttonStateMatrix, Gpio_GetPinState(), Button_Struct::physState, Button_Struct::pinName, and Button_Struct::pressedTimePoint.
Referenced by loop().