Ard-Base: button.cpp File Reference
button.cpp File Reference
#include "gpio.h"
#include <Arduino.h>
#include "button.h"
#include "logger.h"
Macros
#define LOGGER_ENABLED 1
#define LOGGER_LEVEL LOG_INFO
Functions
Button_Struct * Button_FindHandler (Gpio_Pin pinName)
void buttonTask (void)
Variables
Button_Struct buttonStateMatrix []
Macro Definition Documentation
LOGGER_ENABLED
#define LOGGER_ENABLED 1
LOGGER_LEVEL
#define LOGGER_LEVEL LOG_INFO
Function Documentation
Button_FindHandler()
Button_Struct* Button_FindHandler (Gpio_Pin pinName)
References buttonStateMatrix, and Button_Struct::pinName.
Referenced by EventMgrInit().
buttonTask()
void buttonTask (void)
References buttonStateMatrix, Gpio_GetPinState(), Button_Struct::physState, Button_Struct::pinName, and Button_Struct::pressedTimePoint.
Referenced by loop().
Variable Documentation
buttonStateMatrix
Button_Struct buttonStateMatrix[]
Initial value:
= {
    {GPIO_PIN_BUTTON1,  BUTTON_STATE_SHORT_RELEASED, false, 0, },
    {GPIO_PIN_BUTTON2,  BUTTON_STATE_SHORT_RELEASED, false, 0, },
    {GPIO_PIN_BUTTON3,  BUTTON_STATE_SHORT_RELEASED, false, 0, },
    {GPIO_PIN_BUTTON4,  BUTTON_STATE_SHORT_RELEASED, false, 0, },
    {GPIO_PIN_BUTTON5,  BUTTON_STATE_SHORT_RELEASED, false, 0, },
    {GPIO_PIN_BUTTON6,  BUTTON_STATE_SHORT_RELEASED, false, 0, },
    {GPIO_PIN_BUTTON7,  BUTTON_STATE_SHORT_RELEASED, false, 0, },
    {GPIO_PIN_BUTTON8,  BUTTON_STATE_SHORT_RELEASED, false, 0, },
}
Referenced by Button_FindHandler(), and buttonTask().