Ard-Base: event_mgr.h File Reference
event_mgr.h File Reference
#include <stdint.h>
#include <stdbool.h>
#include "actions.h"
Data Structures
struct EventMgr_Config
Enumerations
enum EventMgr_Type { EVENT_TYPE_BUTTON, EVENT_TYPE_TIMER, EVENT_TYPE_SENTINEL }
Functions
void EventMgrInit (void)
void EventMgr_CheckEvents (void)
Enumeration Type Documentation
EventMgr_Type
enum EventMgr_Type
Enumerator
EVENT_TYPE_BUTTON
EVENT_TYPE_TIMER
EVENT_TYPE_SENTINEL
Function Documentation
EventMgr_CheckEvents()
void EventMgr_CheckEvents (void)
References EVENT_TYPE_BUTTON, eventConfigMatrix, and EventMgr_Config::type.
Referenced by loop().
EventMgrInit()
void EventMgrInit (void)
References Button_FindHandler(), EVENT_TYPE_BUTTON, EVENT_TYPE_SENTINEL, EVENT_TYPE_TIMER, eventConfigMatrix, EventMgr_Config::object, EventMgr_Config::objectIndex, Timer_FindHandler(), and EventMgr_Config::type.
Referenced by setup().