Ard-Base: event_mgr.cpp File Reference
event_mgr.cpp File Reference
#include <Arduino.h>
#include "event_mgr.h"
#include "button.h"
#include "timer.h"
#include "actions.h"
#include "logger.h"
Macros
#define LOGGER_ENABLED 1
#define LOGGER_LEVEL LOG_INFO
#define KITCHEN 1
Functions
void EventMgrInit (void)
void EventMgr_CheckEvents (void)
Variables
const Action_Callback * button1CallbackArray [] = {Actions_toggleKitchenMainLight, NULL, Actions_disableKitchAllLight, NULL, Actions_enableKitchenAllLight, NULL}
const Action_Callback * button2CallbackArray [] = {Actions_toggleKitchenLedLight, NULL, Actions_disableKitchAllLight, NULL, Actions_enableKitchenAllLight, NULL}
const Action_Callback * button3CallbackArray [] = {Actions_toggleKitchenMainLight, NULL, Actions_disableKitchAllLight, NULL, Actions_enableKitchenAllLight, NULL}
const Action_Callback * button4CallbackArray [] = {Actions_toggleKitchenLedLight, NULL, Actions_disableKitchAllLight, NULL, Actions_enableKitchenAllLight, NULL}
const Action_Callback * button5CallbackArray [] = {Actions_toggleKitchenMainLight, NULL, Actions_disableKitchAllLight, NULL, Actions_enableKitchenAllLight, NULL}
const Action_Callback * button6CallbackArray [] = {Actions_toggleKitchenLedLight, NULL, Actions_disableKitchAllLight, NULL, Actions_enableKitchenAllLight, NULL}
const Action_Callback * button7CallbackArray [] = {Actions_toggleLivingLightA, NULL, Actions_disableKitchAllLight, NULL, Actions_enableKitchenAllLight, NULL}
const Action_Callback * button8CallbackArray [] = {Actions_toggleLivingLightB, NULL, Actions_disableKitchAllLight, NULL, Actions_enableKitchenAllLight, NULL}
const Action_Callback * sysResetCallbackArray [] = {NULL, NULL, NULL, Actions_toggleLed, Actions_toggleLed,}
const Action_Callback * bedLightCallbackArray [] = {NULL, Actions_enableKitchenLedLight, Actions_disableKitchenLedLight, NULL, NULL,}
EventMgr_Config eventConfigMatrix []
Macro Definition Documentation
KITCHEN
#define KITCHEN 1
LOGGER_ENABLED
#define LOGGER_ENABLED 1
LOGGER_LEVEL
#define LOGGER_LEVEL LOG_INFO
Function Documentation
EventMgr_CheckEvents()
void EventMgr_CheckEvents (void)
References EVENT_TYPE_BUTTON, eventConfigMatrix, and EventMgr_Config::type.
Referenced by loop().
EventMgrInit()
void EventMgrInit (void)
References Button_FindHandler(), EVENT_TYPE_BUTTON, EVENT_TYPE_SENTINEL, EVENT_TYPE_TIMER, eventConfigMatrix, EventMgr_Config::object, EventMgr_Config::objectIndex, Timer_FindHandler(), and EventMgr_Config::type.
Referenced by setup().
Variable Documentation
bedLightCallbackArray
const Action_Callback* bedLightCallbackArray[] = {NULL, Actions_enableKitchenLedLight, Actions_disableKitchenLedLight, NULL, NULL,}
button1CallbackArray
const Action_Callback* button1CallbackArray[] = {Actions_toggleKitchenMainLight, NULL, Actions_disableKitchAllLight, NULL, Actions_enableKitchenAllLight, NULL}
button2CallbackArray
const Action_Callback* button2CallbackArray[] = {Actions_toggleKitchenLedLight, NULL, Actions_disableKitchAllLight, NULL, Actions_enableKitchenAllLight, NULL}
button3CallbackArray
const Action_Callback* button3CallbackArray[] = {Actions_toggleKitchenMainLight, NULL, Actions_disableKitchAllLight, NULL, Actions_enableKitchenAllLight, NULL}
button4CallbackArray
const Action_Callback* button4CallbackArray[] = {Actions_toggleKitchenLedLight, NULL, Actions_disableKitchAllLight, NULL, Actions_enableKitchenAllLight, NULL}
button5CallbackArray
const Action_Callback* button5CallbackArray[] = {Actions_toggleKitchenMainLight, NULL, Actions_disableKitchAllLight, NULL, Actions_enableKitchenAllLight, NULL}
button6CallbackArray
const Action_Callback* button6CallbackArray[] = {Actions_toggleKitchenLedLight, NULL, Actions_disableKitchAllLight, NULL, Actions_enableKitchenAllLight, NULL}
button7CallbackArray
const Action_Callback* button7CallbackArray[] = {Actions_toggleLivingLightA, NULL, Actions_disableKitchAllLight, NULL, Actions_enableKitchenAllLight, NULL}
button8CallbackArray
const Action_Callback* button8CallbackArray[] = {Actions_toggleLivingLightB, NULL, Actions_disableKitchAllLight, NULL, Actions_enableKitchenAllLight, NULL}
eventConfigMatrix
EventMgr_Config eventConfigMatrix[]
Initial value:
= {
    [0]  = {EVENT_TYPE_BUTTON, 0, NULL, GPIO_PIN_BUTTON1,  0, button1CallbackArray,  },
    [1]  = {EVENT_TYPE_BUTTON, 0, NULL, GPIO_PIN_BUTTON2,  0, button2CallbackArray,  },
    [2]  = {EVENT_TYPE_BUTTON, 0, NULL, GPIO_PIN_BUTTON3,  0, button3CallbackArray,  },
    [3]  = {EVENT_TYPE_BUTTON, 0, NULL, GPIO_PIN_BUTTON4,  0, button4CallbackArray,  },
    [4]  = {EVENT_TYPE_BUTTON, 0, NULL, GPIO_PIN_BUTTON5,  0, button5CallbackArray,  },
    [5]  = {EVENT_TYPE_BUTTON, 0, NULL, GPIO_PIN_BUTTON6,  0, button6CallbackArray,  },
    [6]  = {EVENT_TYPE_BUTTON, 0, NULL, GPIO_PIN_BUTTON7,  0, button7CallbackArray,  },
    [7]  = {EVENT_TYPE_BUTTON, 0, NULL, GPIO_PIN_BUTTON8,  0, button8CallbackArray,  },
    [8] = {EVENT_TYPE_TIMER,  0, NULL, TIMER_SYS_RUN,     0, sysResetCallbackArray, },
    [9] = {EVENT_TYPE_TIMER,  0, NULL, TIMER_BED_LIGHT,   0, bedLightCallbackArray, },
}
Referenced by EventMgr_CheckEvents(), and EventMgrInit().
sysResetCallbackArray
const Action_Callback* sysResetCallbackArray[] = {NULL, NULL, NULL, Actions_toggleLed, Actions_toggleLed,}