Ard-Base: gpio.h File Reference
gpio.h File Reference
#include "stdint.h"
#include "stdbool.h"
Data Structures
struct Gpio_Config
blabla
Enumerations
enum Gpio_Pin {
GPIO_PIN_LED, GPIO_PIN_RELAY1, GPIO_PIN_RELAY2, GPIO_PIN_RELAY3,
GPIO_PIN_RELAY4, GPIO_PIN_BUTTON1, GPIO_PIN_BUTTON2, GPIO_PIN_BUTTON3,
GPIO_PIN_BUTTON4, GPIO_PIN_BUTTON5, GPIO_PIN_BUTTON6, GPIO_PIN_BUTTON7,
GPIO_PIN_BUTTON8, GPIO_PIN_SENTINEL
}
Functions
void Gpio_Init (void)
Initialize gpio unit.
bool Gpio_GetPinState (Gpio_Pin pinName)
Get pin state.
void Gpio_SetPinState (Gpio_Pin pinName, bool state)
Set pin state to High(true) or Low(false)
Enumeration Type Documentation
Gpio_Pin
enum Gpio_Pin
Enumerator
GPIO_PIN_LED
GPIO_PIN_RELAY1
GPIO_PIN_RELAY2
GPIO_PIN_RELAY3
GPIO_PIN_RELAY4
GPIO_PIN_BUTTON1
GPIO_PIN_BUTTON2
GPIO_PIN_BUTTON3
GPIO_PIN_BUTTON4
GPIO_PIN_BUTTON5
GPIO_PIN_BUTTON6
GPIO_PIN_BUTTON7
GPIO_PIN_BUTTON8
GPIO_PIN_SENTINEL
Function Documentation
Gpio_GetPinState()
bool Gpio_GetPinState (Gpio_Pin pinName)
Get pin state.
Parameters
[in] pinName enumed name of the pin
Return values
true pin is in the High state
false pin is in the Low state
References Gpio_Config::isInvertedLogic, and Gpio_Config::pinNumber.
Referenced by Actions_toggleKitchenLedLight(), Actions_toggleKitchenMainLight(), Actions_toggleLed(), Actions_toggleLivingLightA(), Actions_toggleLivingLightB(), Actions_toggleMainLight(), Actions_toggleWallLightA(), Actions_toggleWallLightB(), and buttonTask().
Gpio_Init()
void Gpio_Init (void)
Initialize gpio unit.
References LOG_INFO, and LOGGERLN.
Referenced by setup().
Gpio_SetPinState()
void Gpio_SetPinState (Gpio_Pin pinName, bool state)
Set pin state to High(true) or Low(false)
Parameters
[in] pinName enumed name of the pin to drive
[in] state true to drive High or false to drive Low
References Gpio_Config::isInvertedLogic, LOG_DEBUG, LOGGER, LOGGERLN, and Gpio_Config::pinNumber.
Referenced by Actions_disableAllLight(), Actions_disableBedLight(), Actions_disableKitchAllLight(), Actions_disableKitchenLedLight(), Actions_disableLivingLight(), Actions_disableLivingLightA(), Actions_disableLivingLightB(), Actions_disableWallLight(), Actions_disableWallLightA(), Actions_disableWallLightB(), Actions_enableAllLight(), Actions_enableBedLight(), Actions_enableKitchenAllLight(), Actions_enableKitchenLedLight(), Actions_enableLivingLight(), Actions_enableLivingLightA(), Actions_enableLivingLightB(), Actions_enableWallLight(), Actions_enableWallLightA(), Actions_enableWallLightB(), Actions_toggleKitchenLedLight(), Actions_toggleKitchenMainLight(), Actions_toggleLed(), Actions_toggleLivingLightA(), Actions_toggleLivingLightB(), Actions_toggleMainLight(), Actions_toggleWallLightA(), and Actions_toggleWallLightB().