Ard-Base: gpio.cpp File Reference
gpio.cpp File Reference
#include "gpio.h"
#include <Arduino.h>
#include <assert.h>
#include "logger.h"
Macros
#define LOGGER_ENABLED 1
#define LOGGER_LEVEL LOG_INFO
Functions
void Gpio_Init (void)
Initialize gpio unit.
bool Gpio_GetPinState (Gpio_Pin pinName)
Get pin state.
void Gpio_SetPinState (Gpio_Pin pinName, bool state)
Set pin state to High(true) or Low(false)
Variables
const Gpio_Config gpioHardwareConfigTab []
Macro Definition Documentation
LOGGER_ENABLED
#define LOGGER_ENABLED 1
LOGGER_LEVEL
#define LOGGER_LEVEL LOG_INFO
Function Documentation
Gpio_GetPinState()
bool Gpio_GetPinState (Gpio_Pin pinName)
Get pin state.
Parameters
[in] pinName enumed name of the pin
Return values
true pin is in the High state
false pin is in the Low state
References Gpio_Config::isInvertedLogic, and Gpio_Config::pinNumber.
Referenced by Actions_toggleKitchenLedLight(), Actions_toggleKitchenMainLight(), Actions_toggleLed(), Actions_toggleLivingLightA(), Actions_toggleLivingLightB(), Actions_toggleMainLight(), Actions_toggleWallLightA(), Actions_toggleWallLightB(), and buttonTask().
Gpio_Init()
void Gpio_Init (void)
Initialize gpio unit.
References LOG_INFO, and LOGGERLN.
Referenced by setup().
Gpio_SetPinState()
void Gpio_SetPinState (Gpio_Pin pinName, bool state)
Set pin state to High(true) or Low(false)
Parameters
[in] pinName enumed name of the pin to drive
[in] state true to drive High or false to drive Low
References Gpio_Config::isInvertedLogic, LOG_DEBUG, LOGGER, LOGGERLN, and Gpio_Config::pinNumber.
Referenced by Actions_disableAllLight(), Actions_disableBedLight(), Actions_disableKitchAllLight(), Actions_disableKitchenLedLight(), Actions_disableLivingLight(), Actions_disableLivingLightA(), Actions_disableLivingLightB(), Actions_disableWallLight(), Actions_disableWallLightA(), Actions_disableWallLightB(), Actions_enableAllLight(), Actions_enableBedLight(), Actions_enableKitchenAllLight(), Actions_enableKitchenLedLight(), Actions_enableLivingLight(), Actions_enableLivingLightA(), Actions_enableLivingLightB(), Actions_enableWallLight(), Actions_enableWallLightA(), Actions_enableWallLightB(), Actions_toggleKitchenLedLight(), Actions_toggleKitchenMainLight(), Actions_toggleLed(), Actions_toggleLivingLightA(), Actions_toggleLivingLightB(), Actions_toggleMainLight(), Actions_toggleWallLightA(), and Actions_toggleWallLightB().
Variable Documentation
gpioHardwareConfigTab
const Gpio_Config gpioHardwareConfigTab[]
Initial value:
= {
    [GPIO_PIN_LED]     = {13,    false,  false,   false,  HIGH},
    [GPIO_PIN_RELAY1]  = {A0,    false,  false,   true,   LOW},
    [GPIO_PIN_RELAY2]  = {A1,    false,  false,   true,   LOW},
    [GPIO_PIN_RELAY3]  = {A2,    false,  false,   true,   LOW},
    [GPIO_PIN_RELAY4]  = {A3,    false,  false,   true,   LOW},
    [GPIO_PIN_BUTTON1] = { 2,    true,   false,   true,  0},
    [GPIO_PIN_BUTTON2] = { 3,    true,   false,   true,  0},
    [GPIO_PIN_BUTTON3] = { 4,    true,   false,   true,  0},
    [GPIO_PIN_BUTTON4] = { 5,    true,   false,   true,  0},
    [GPIO_PIN_BUTTON5] = { 6,    true,   false,   true,  0},
    [GPIO_PIN_BUTTON6] = { 7,    true,   false,   true,  0},
    [GPIO_PIN_BUTTON7] = { 8,    true,   false,   true,  0},
    [GPIO_PIN_BUTTON8] = { 9,    true,   false,   true,  0},
}