Ard-Base: sketch_aug19a.ino File Reference
sketch_aug19a.ino File Reference
#include "gpio.h"
#include "button.h"
#include "timer.h"
#include "event_mgr.h"
#include "logger.h"
Macros
#define LOGGER_ENABLED 1
#define LOGGER_LEVEL LOG_INFO
Functions
void setup ()
void loop ()
Macro Definition Documentation
LOGGER_ENABLED
#define LOGGER_ENABLED 1
LOGGER_LEVEL
#define LOGGER_LEVEL LOG_INFO
Function Documentation
loop()
void loop ()
References buttonTask(), EventMgr_CheckEvents(), and Timer_TaskMain().
setup()
void setup ()
References EventMgrInit(), Gpio_Init(), LOG_INFO, LOGGERLN, Timer_Run(), and TIMER_SYS_RUN.