Ard-Base: timer.h File Reference
timer.h File Reference
#include "stdint.h"
#include "stdbool.h"
Data Structures
struct Timer_Struct
Macros
#define SEC_TO_MS(T) ((T)*1000uL)
#define MIN_TO_MS(T) ((T)*1000uL*60uL)
#define HOUR_TO_MS(T) ((T)*1000uL*60uL*60uL)
Typedefs
typedef void(* Timer_Callback) (void)
Enumerations
enum Timer_Name { TIMER_SYS_RUN, TIMER_BED_LIGHT, TIMER_NAME_SENTINEL }
enum Timer_State {
TIMER_STOPPED, TIMER_RUNNING, TIMER_EXPIRED, TIMER_EXPIRED_PERIOD_A,
TIMER_EXPIRED_PERIOD_B, TIMER_SENTINEL
}
Functions
void Timer_TaskMain (void)
Timer_Struct * Timer_FindHandler (Timer_Name timerName)
void Timer_Stop (Timer_Name timerName)
void Timer_Run (Timer_Name timerName)
Macro Definition Documentation
HOUR_TO_MS
#define HOUR_TO_MS (T) ((T)*1000uL*60uL*60uL)
MIN_TO_MS
#define MIN_TO_MS (T) ((T)*1000uL*60uL)
SEC_TO_MS
#define SEC_TO_MS (T) ((T)*1000uL)
Typedef Documentation
Timer_Callback
typedef void(* Timer_Callback) (void)
Enumeration Type Documentation
Timer_Name
enum Timer_Name
Enumerator
TIMER_SYS_RUN
TIMER_BED_LIGHT
TIMER_NAME_SENTINEL
Timer_State
enum Timer_State
Enumerator
TIMER_STOPPED
TIMER_RUNNING
TIMER_EXPIRED
TIMER_EXPIRED_PERIOD_A
TIMER_EXPIRED_PERIOD_B
TIMER_SENTINEL
Function Documentation
Timer_FindHandler()
Timer_Struct* Timer_FindHandler (Timer_Name timerName)
Referenced by EventMgrInit().
Timer_Run()
void Timer_Run (Timer_Name timerName)
References LOG_DEBUG, LOG_INFO, LOGGER, LOGGERLN, Timer_Struct::startingTime, Timer_Struct::state, and TIMER_RUNNING.
Referenced by Actions_runBedLightTimer(), and setup().
Timer_Stop()
void Timer_Stop (Timer_Name timerName)
References LOG_DEBUG, LOG_INFO, LOGGER, LOGGERLN, Timer_Struct::state, and TIMER_STOPPED.
Referenced by Actions_enableBedLight().
Timer_TaskMain()
void Timer_TaskMain (void)
References Timer_Struct::state, TIMER_EXPIRED, TIMER_EXPIRED_PERIOD_A, TIMER_EXPIRED_PERIOD_B, TIMER_RUNNING, TIMER_STOPPED, and timerStateMatrix.
Referenced by loop().