Ard-Base: timer.cpp File Reference
timer.cpp File Reference
#include "Arduino.h"
#include "timer.h"
#include "logger.h"
Macros
#define LOGGER_ENABLED 1
#define LOGGER_LEVEL LOG_DEBUG
Functions
void timeoutDetected (Timer_Struct *timer)
void Timer_TaskMain (void)
Timer_Struct * Timer_FindHandler (Timer_Name timerName)
void Timer_Run (Timer_Name timerName)
void Timer_Stop (Timer_Name timerName)
Variables
Timer_Struct timerStateMatrix []
Macro Definition Documentation
LOGGER_ENABLED
#define LOGGER_ENABLED 1
LOGGER_LEVEL
#define LOGGER_LEVEL LOG_DEBUG
Function Documentation
timeoutDetected()
void timeoutDetected (Timer_Struct * timer)
References Timer_Struct::isPeriodic, LOG_DEBUG, LOG_INFO, LOGGER, Timer_Struct::startingTime, Timer_Struct::state, Timer_Struct::timeout, TIMER_EXPIRED, TIMER_EXPIRED_PERIOD_A, TIMER_EXPIRED_PERIOD_B, TIMER_RUNNING, TIMER_SENTINEL, and TIMER_STOPPED.
Timer_FindHandler()
Timer_Struct* Timer_FindHandler (Timer_Name timerName)
Referenced by EventMgrInit().
Timer_Run()
void Timer_Run (Timer_Name timerName)
References LOG_DEBUG, LOG_INFO, LOGGER, LOGGERLN, Timer_Struct::startingTime, Timer_Struct::state, and TIMER_RUNNING.
Referenced by Actions_runBedLightTimer(), and setup().
Timer_Stop()
void Timer_Stop (Timer_Name timerName)
References LOG_DEBUG, LOG_INFO, LOGGER, LOGGERLN, Timer_Struct::state, and TIMER_STOPPED.
Referenced by Actions_enableBedLight().
Timer_TaskMain()
void Timer_TaskMain (void)
References Timer_Struct::state, TIMER_EXPIRED, TIMER_EXPIRED_PERIOD_A, TIMER_EXPIRED_PERIOD_B, TIMER_RUNNING, TIMER_STOPPED, and timerStateMatrix.
Referenced by loop().
Variable Documentation
timerStateMatrix
Timer_Struct timerStateMatrix[]
Initial value:
= {
    [TIMER_SYS_RUN] =   {TIMER_STOPPED, true,  0, 500uL},
    [TIMER_BED_LIGHT] = {TIMER_STOPPED, false, 0, SEC_TO_MS(10uL)},
}
Referenced by Timer_TaskMain().